### ISSUE TITLE
Chain Params: add MaxBlockSize

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#796]
Chain Params page currently has MaxTxSize(393216 bytes, "Largest allowable transaction size") but no MaxBlockSize.

Decred mainnet maximum block size is not the same as Bitcoin and seems it is not a well known fact, which often leads to confusion ([example 1](https://www.reddit.com/r/decred/comments/9ug4ij/decred_features_as_our_spotlight_of_the_week/e944ek6/), [example 2](https://www.reddit.com/r/decred/comments/7xzglu/how_many_transactions_per_second_can_decred_handle/ducsrey/)). It is an important parameter that needs more exposure.

**Comment by buck54321** [comment]
I think this was addressed by #715. I have it locally.

**Comment by xaur** [comment]
Was unaware of that PR, feel free to close when appropriate.

**Comment by chappjc** [comment]
It's partially addressed.  Since `MaximumBlockSizes` is an array, and we are just taking the first element, the displayed block size can be incorrect after a block size increase agenda item passes but before the next software update.
